sonar.organization=ismaildurmaz
sonar.projectKey=ismaildurmaz_segsql
sonar.projectName=Segmented SQL Builder

sonar.sourceEncoding=UTF-8
sonar.language=gov0

# Sources
sonar.sources=.
sonar.exclusions=**/vendor/**,**/*_test.go

# Tests
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Coverage
sonar.go.coverage.reportPaths=**/build/reports/coverage.out

# Unit test reports
sonar.go.tests.reportPaths=**/build/reports/test-results/go-test.xml

# GolangCI-Lint
sonar.go.golangci-lint.reportPaths=**/build/reports/golangci-lint.xml


